version: '3'
services:
  dokkoi:
    image: golang:1.17
    working_dir: /dokkoi
    volumes:
      - .:/dokkoi
      - gomod_cache:/go
    command: bash -c "go run ./cmd/dokkoi"
    environment:
      DISCORD_TOKEN: $DISCORD_TOKEN
      CUSTOMSEARCH_API_KEY: $CUSTOMSEARCH_API_KEY
      CUSTOMSEARCH_ENGINE_ID: $CUSTOMSEARCH_ENGINE_ID
    ports:
      - 10000:10000
    depends_on:
      - redis
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379

volumes:
  gomod_cache: {}
