// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/johnmanjiro13/dokkoi/command (interfaces: ScoreRepository)

// Package mock_command is a generated GoMock package.
package mock_command

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockScoreRepository is a mock of ScoreRepository interface
type MockScoreRepository struct {
	ctrl     *gomock.Controller
	recorder *MockScoreRepositoryMockRecorder
}

// MockScoreRepositoryMockRecorder is the mock recorder for MockScoreRepository
type MockScoreRepositoryMockRecorder struct {
	mock *MockScoreRepository
}

// NewMockScoreRepository creates a new mock instance
func NewMockScoreRepository(ctrl *gomock.Controller) *MockScoreRepository {
	mock := &MockScoreRepository{ctrl: ctrl}
	mock.recorder = &MockScoreRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockScoreRepository) EXPECT() *MockScoreRepositoryMockRecorder {
	return m.recorder
}

// Decr mocks base method
func (m *MockScoreRepository) Decr(arg0 string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decr", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// Decr indicates an expected call of Decr
func (mr *MockScoreRepositoryMockRecorder) Decr(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decr", reflect.TypeOf((*MockScoreRepository)(nil).Decr), arg0)
}

// Incr mocks base method
func (m *MockScoreRepository) Incr(arg0 string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Incr", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// Incr indicates an expected call of Incr
func (mr *MockScoreRepositoryMockRecorder) Incr(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Incr", reflect.TypeOf((*MockScoreRepository)(nil).Incr), arg0)
}

// LastUser mocks base method
func (m *MockScoreRepository) LastUser() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastUser")
	ret0, _ := ret[0].(string)
	return ret0
}

// LastUser indicates an expected call of LastUser
func (mr *MockScoreRepositoryMockRecorder) LastUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastUser", reflect.TypeOf((*MockScoreRepository)(nil).LastUser))
}

// UserScore mocks base method
func (m *MockScoreRepository) UserScore(arg0 string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserScore", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// UserScore indicates an expected call of UserScore
func (mr *MockScoreRepositoryMockRecorder) UserScore(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserScore", reflect.TypeOf((*MockScoreRepository)(nil).UserScore), arg0)
}
